const action_types = {
    LOAD_BOARDS: "LOAD-BOARDS",
    RESET_BOARDS: "RESET",
    LOAD_CURRENT: "LOAD-CURRENT",
    RESET_CURRENT: "RESET-CURRENT",
    SET_CURRENT: "SET-CURRENT",
    SHIFT_SELECTED: "SHIFT-SELECTED",
    PUSH_SELECTED: "PUSH-SELECTED",
    UPDATE_TIME: "PLAYING-SINCE",
    ANNOTATE: "ANNOTATE",
    DELETE_ANNOTATION: "DELETE-ANNOTATION",
    LOAD_SAVED: "LOAD-SAVED",
    LOAD_RESPONSE: "LOAD-RESPONSE",
    DELETE_ALL_ANNOTATIONS: "DELETE_ALL_ANNOTATIONS"
}

export default action_types